"""empty message

Revision ID: 00734f824256
Revises: 139f2811bbed
Create Date: 2024-05-22 19:23:22.692127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00734f824256'
down_revision = '139f2811bbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('sintoms', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diseases')
    # ### end Alembic commands ###
